remove_item_loc = "(//a[@title='Remove This Item'])"
pop_up_ok_button_loc = "(//button[@class='action-primary action-accept'])"
delete_item_icon_loc = "(//a[@class='action delete'])"
email_field_loc = "(//input[@name='login[username]'])"
password_field_loc = "(//input[@name='login[password]'])"
sign_in_button_loc = "(//button[@class='action login primary'])"
text_message = "(//div[@data-bind='html: $parent.prepareMessageForHtml(message.text)'])"
menu_button_loc = "(//button[@data-action='customer-menu-toggle'])[1]"
sign_out_loc = "Sign Out"
logged_in_loc = "(//span[@class='logged-in'])[1]"
